podTemplate(containers: [containerTemplate(image: 'docker', name: 'docker', command: 'sleep', args: '99d')]) {
    podTemplate(containers: [containerTemplate(image: 'maven', name: 'maven', command: 'sleep', args: '99d')]) {
      node("kubepods") { // gets a pod with both docker and maven
        sh "echo hello ankit bhai"
      }
    }
}
