pipeline {
    agent any 
    stages {
        stage('Build') { 
            steps {
                echo "This is Build stage 1."
            }
        }
        stage('Test') { 
            steps {
                echo "This is Test stage." 
            }
        }
        stage('Deploy') { 
            steps {
                echo "This is Deploy stage." 
            }
        }
    }
}
