pipeline {
  agent {
    kubernetes {
      inheritFrom 'Kube_jenkins_agent'
      yaml '''
      spec:
        containers:
        - name: maven
          image: maven:3.9.9-eclipse-temurin-21
'''
      …
    }
  }
  stages {
    stage ("print name"){
        steps{
        sh "echo hello"
        
        }
    }
  }
}
